language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint src
deploy:
- provider: script
  script: ./setup.py bdist_wheel && ./scripts/publish.sh
  on:
    tags: true
    branch: master
