apiVersion: batch/v1
kind: Job
metadata:
  name: a01droidrun
spec:
  template:
    metadata:
      name: a01droidrun
    spec:
      containers:
      - name: a01droid
        image: a01reg.azurecr.io/a01droid:0.0.5
        command: ["python",  "/app/job.py", "a01store", "2"]
        env:
        - name: ENV_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ENV_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Never
  backoffLimit: 2
